config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root to: 'teams#index'
  resources :teams do
    resources :askings do
      collection do
        get 'choose'
        get 'search'
      end
    end
    resources :emails do
      collection do
        get 'choose'
        get 'search'
      end
    end
  end
  resources :users, only: [:index, :show, :destroy]
  resources :manuals do
    resources :comments, only: [:create, :edit, :update, :destroy]
    collection do
      get 'search'
      get 'each'
    end
  end
  resources :calendars, only: [:index, :new, :create, :destroy]
end

app/models/asking.rb
class Asking < ApplicationRecord

  validates :question, presence: true
  validates :answer,    presence: true

  belongs_to :user
  belongs_to :team

  acts_as_taggable
  acts_as_taggable_on :skills, :interests

  def new_arrival?
    created_at + 1.week > Date.today
  end
end

app/controllers/askings_controller.rb
class AskingsController < ApplicationController
  before_action :set_asking, only: [:show, :edit, :update]
  before_action :find_team, only: [:choose, :new, :create, :search]
  before_action :find_tag, only: [:choose, :new, :edit, :show]

  def index
    @teams = Team.all
  end

  def choose
    @askings = @team.askings.includes(:user).order("created_at DESC").page(params[:page]).per(20)
  end

  def new
    @asking = Asking.new
  end

  def create
    @asking = @team.askings.new(asking_params)
    if @asking.save
      redirect_to choose_team_askings_path(@team)
    else
      render :new
    end
  end

  def show
  end

  def edit
    unless current_user.id == @asking.user_id
      redirect_to action: :show
    end
  end

  def update
    if @asking.update(asking_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    team = Team.find(params[:team_id])
    asking = team.askings.find(params[:id])
    unless current_user.id == asking.user_id
      redirect_to action: :show
    end
    asking.destroy
    return redirect_to action: :choose
  end

  def search
    if params[:q]&.dig(:question)
      squished_keywords = params[:q][:question].squish
      params[:q][:question_or_answer_cont_any] = squished_keywords.split(" ")
    end
    @q = @team.askings.ransack(params[:q])
    @askings = @q.result.order("created_at DESC").page(params[:page]).per(20)
  end

  private

  def asking_params
    params.require(:asking).permit(:question, :answer, :tag_list).merge(user_id: current_user.id)
  end

  def set_asking
    @team = Team.find(params[:team_id])
    @asking = @team.askings.find(params[:id])
  end

  def find_team
    @team = Team.find(params[:team_id])
  end

  def find_tag
    @tags = @team.askings.tag_counts_on(:tags).most_used(20)
    if @tag = params[:tag]
      @asking = @team.askings.tagged_with(params[:tag])
    end
  end

end

app/helpers/askings_helper.rb
module AskingsHelper
end

app/views/askings/_form.html.erb
<div class="asking-create-form">
  <%= form_with(model: [team, asking],url: asking.new_record? ? team_askings_path : team_asking_path(team.id, asking.id), local: true) do |form| %>
    <%= render 'layouts/error_messages', model: form.object %>
    <div class="asking-field">
      <h4>質問内容</h4>
      <%= form.text_area :question, placeholder: "質問", size: "70x5" %>
    </div>
    <div class="asking-field">
      <h4>回答内容</h4>
      <%= form.text_area :answer, placeholder: "回答", size: "70x5" %>
    </div>
    <div class="asking-field">
      <h4>タグ名</h4>
      <%= form.text_field :tag_list, placeholder: "タグ名", size: "40" %>
        <div class="form-tag">既存のタグ：
          <% @tags.each do |tag| %>
            <%= tag.name %> /
          <% end %>
        </div>
    </div>

    <% if local_assigns[:edit_flag].present? %>
      <%= form_with(model: [team, asking],url: asking.new_record? ? team_askings_path : team_asking_path(team.id, asking.id), local: true) do |form| %>
        <div class="asking-btn">
          <%= form.submit "編集する", class: "btn btn-danger" %>
        </div>
      <% end %>
    <% else %>
      <%= form_with(model: [team, asking],url: asking.new_record? ? team_askings_path : team_asking_path(team.id, asking.id), local: true) do |form| %>
        <div class="asking-btn">
          <%= form.submit "投稿する", class: "btn btn-danger" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/askings/_search.html.erb
<div class="search">
  <div class="search-title">問い合わせ検索</div>
  <%= search_form_for @team.askings.ransack(params[:q]), url: search_team_askings_path do |f| %>
    <div class="search-field">
      <% f.label :question_or_answer_cont, '検索キーワード' %>
      <%= f.text_field :question_or_answer_cont, placeholder: '検索キーワード' %>
    </div>
    <div class="search-field">
      <%= f.label :submit, class: "search-button" do %>
        <input type= "submit" value="検索" class="btn btn-danger search-btn">
        <%= f.submit :submit, id: "q_submit", style: "display: none;" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/askings/choose.html.erb
<h2>問い合わせ：<%= @team.name %></h2>
<% breadcrumb :asking_choose, @team %>

<div class="asking-create">
  <%= link_to "問い合わせを作成する", new_team_asking_path, class: "btn btn-outline-danger" %>
</div>

<div class="asking">
  <div class="asking-body">
    <div class="asking-team">
      <%= @team.name %>の問い合わせ一覧
    </div>

    <%# タグ機能 %>
    <div class="tag">
      <div class="tag-top"><b>タグ一覧</b></div>
      <% if @tags.present? %>
        <div class="tags">
          <% @tags.each do |tag| %>
            <div><%= link_to "#{tag.name}(#{tag.taggings_count})", choose_team_askings_path(tag: tag.name), class: "link" %></div>
          <% end %>
        </div>
      <% else %>
          <P>登録されているタグはありません</p>
      <% end %>

      <% if @asking.present? %>
        <div class="tag-top"><b><%= "タグ：#{@tag}" %></b></div>
        <div class="tags">
          <% @asking.each do |asking| %>
            <%= link_to asking.question, team_asking_path(@team.id, asking.id), method: :get, class: "link" %><br>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="all-asking">
      <div class="asking-top"><b>問い合わせ</b></div>
      <% @askings.each do |asking| %>
        <ul>
          <li>
            <div class="news">
              <div class="newlabel">
                <%= render 'shared/new_label' if asking.new_arrival? %>
              </div>
              <%= link_to asking.question, team_asking_path(@team.id, asking.id), method: :get, class: "link" %>
            </div>
          </li>
        </ul>
      <% end %>
    </div>

    <%= paginate @askings %>
  </div>
  <%# 検索機能 %>
  <div class="search-form">
    <%= render 'search', url: search_team_askings_path, q: @q %>
  </div>

</div>

app/views/askings/edit.html.erb
<h2>問い合わせ</h2>
<% breadcrumb :asking_edit, @team, @asking %>
<div class="asking-container">
  <div class="asking">
    <div class="asking-body">
      <div class="asking-all">問い合わせ編集</div>
    </div>
  </div>

  <div class="asking-form">
    <%= render partial: "form", locals: { team: @team, asking: @asking, edit_flag: true } %>
  </div>
</div>

app/views/askings/index.html.erb
<h2>問い合わせ</h2>
<% breadcrumb :asking_index %>
<div class="asking">
  <div class="asking-index">
    <div class="asking-team">確認したい所属を選ぶ</div>
    <% current_user.teams.each do |team| %>
      <ul>
        <li>
          <div class="niko">☺︎</div>
          <%= link_to team.name, choose_team_askings_path(team), method: :get, class: "link" %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/askings/new.html.erb
<h2>問い合わせ</h2>
<% breadcrumb :asking_new, @team %>
<div class="asking-container">
  <div class="asking">
    <div class="asking-body">
      <div class="asking-all">問い合わせ新規作成</div>
    </div>
  </div>

  <div class="asking-form">
    <%= render partial: "form", locals: { team: @team, asking: @asking}%>
  </div>
</div>

app/views/askings/search.html.erb
<h2>問い合わせ：<%= @team.name %></h2>
<% breadcrumb :asking_search, @team, @asking %>

<div class="asking-create">
  <%= link_to "問い合わせを作成する", new_team_asking_path, class: "btn btn-outline-danger" %>
</div>

<div class="result">検索結果</div>

<div class="asking">
  <%# 問い合わせ検索結果 %>
  <div class="asking-body">
    <% if @askings.present? %>
      <div class="all-asking">
        <% @askings.each do |asking| %>
          <ul>
            <li>
              <div class="news">
                <div class="newlabel">
                  <%= render 'shared/new_label' if asking.new_arrival? %>
                </div>
                <%= link_to asking.question, team_asking_path(@team.id, asking.id), method: :get, class: "link" %>
              </div>
            </li>
          </ul>
        <% end %>
      </div>
    <% else %>
      <p>キーワードに該当する問い合わせはありません</p>
    <% end %>
  </div>

  <%# 検索機能 %>
  <div class="search-form">
    <div class="search-form">
      <%= render 'search', url: search_team_askings_path, q: @q %>
    </div>
  </div>
</div>

app/views/askings/show.html.erb
<h2>問い合わせ：<%= @team.name %></h2>
<% breadcrumb :asking_show, @team, @asking %>

<div class="asking-create">
  <%= link_to "問い合わせを作成する", new_team_asking_path, class: "btn btn-outline-danger" %>
</div>

<div class="edit">
  <% if current_user.id == @asking.user_id %>
    <%= link_to '編集', edit_team_asking_path(@team.id, @asking.id), class: "link" %>
    <%= link_to '削除', team_asking_path(@team.id, @asking.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "link" %>
  <% end %>
</div>

<div class="asking">
  <div class="asking-body">
    <div class="asking-show">タグ</div>
    <% if @tags.present? %>
      <div class="tags">
        <% @asking.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
      </div>
    <% else %>
      <P>タグは登録されていません</p>
    <% end %>

    <div class="asking-show">質問内容</div>
    <div  style="position: relative; margin: 1em 0 1em 20px; border-radius: 10px; background: #dcdcdc; font-size: 100%; padding: 20px; width: 400px; ">
      <%= simple_format(@asking.question) %>
      <span  style="position: absolute; top: 50%; left: -30px; margin-top: -15px;  border: 15px solid transparent;  border-right: 20px solid #dcdcdc; width: 0;  height: 0;"></span>
    </div>

    <div class="asking-show">回答内容</div>
    <div  style="position: relative; margin: 1em 0 1em 20px; border-radius:10px; background: #dcdcdc; font-size: 100%; padding: 20px; width: 400px;">
      <%= simple_format(@asking.answer) %>
      <span  style="position: absolute; top: 50%; right: -30px; margin-top: -15px;  border: 15px solid transparent;  border-left: 20px solid #dcdcdc; width: 0;  height: 0;"></span>
    </div>


    <div class="asking-show">投稿者</div>
    <div class="show-cont">
      <%= @asking.user.full_name %>
    </div>

    <div class="asking-show">投稿日</div>
    <div class="show-cont">
      <%= @asking.created_at.strftime('%Y年%m月%d日') %>
    </div>
  </div>

  <%# 検索機能 %>
  <div class="search-form">
    <%= render 'search', url: search_team_askings_path, q: @q %>
  </div>
</div>