config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root to: 'teams#index'
  resources :teams do
    resources :askings do
      collection do
        get 'choose'
        get 'search'
      end
    end
    resources :emails do
      collection do
        get 'choose'
        get 'search'
      end
    end
  end
  resources :users, only: [:index, :show, :destroy]
  resources :manuals do
    resources :comments, only: [:create, :edit, :update, :destroy]
    collection do
      get 'search'
      get 'each'
    end
  end
  resources :calendars, only: [:index, :new, :create, :destroy]
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  validates :title, presence: true
  validates :start_time, presence: true
  
  belongs_to :user
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  before_action :set_biginning_of_week
  def index
    @calendars = Calendar.all
    @calendar = Calendar.new
  end
  
  def new
    @calendar = Calendar.new
  end

  def create
    Calendar.create(calendar_params)
    redirect_to calendars_path
  end

  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    redirect_to calendars_path, notice: "削除しました"
  end

  private
  def set_biginning_of_week
    Date.beginning_of_week = :sunday
  end

  def calendar_params
    params.require(:calendar).permit(:title, :start_time).merge(user_id: current_user.id)
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/index.html.erb
<h2>業務管理</h2>
<% breadcrumb :calendar_index %>

<div class="calendar">
  <div class="calendar-form">
    <%= form_with(model: @calendar, local: true) do |form| %>
      <div class="title">
        <div class="form-tag"><b>業務内容</b></div>
        <%= form.text_field :title %>
      </div>

      <div class="time">
        <div class="form-tag"><b>日付</b></div>
        <%= raw sprintf(
          form.date_select(
            :start_time,
            use_month_numbers: true,
            end_year: (Time.now.year),
            date_separator: '%s'),
          '年', '月') + '日' %>
      </div>

      <div class="submit">
        <%= form.submit "カレンダーに追加" %>
      </div>
    <% end %>
  </div>

  <div class="calendar-show">
    <%= month_calendar events: @calendars do |date, calendars| %>
      <%= date.day %>
      <% calendars.each do |calendar| %>
        <div>
          <%= calendar.title %>
          <%= link_to "削除", calendar_path(@calendars.ids), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "link-calendar" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>