config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  root to: 'teams#index'
  resources :teams do
    resources :askings do
      collection do
        get 'choose'
        get 'search'
      end
    end
    resources :emails do
      collection do
        get 'choose'
        get 'search'
      end
    end
  end
  resources :users, only: [:index, :show, :destroy]
  resources :manuals do
    resources :comments, only: [:create, :edit, :update, :destroy]
    collection do
      get 'search'
      get 'each'
    end
  end
  resources :calendars, only: [:index, :new, :create, :destroy]
end

app/models/manual.rb
class Manual < ApplicationRecord
  validates :title, presence: true
  validates :manual_text, presence: true
  
  belongs_to :user
  belongs_to :team
  has_many :comments, dependent: :destroy

  mount_uploader :shiryo, ShiryoUploader

  def new_arrival?
    created_at + 1.week > Date.today
  end
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  before_action :set_manual, only: [:show, :edit, :update]

  def index
    @manuals = Manual.includes(:user).order("created_at DESC")
  end

  def new
    @manual = Manual.new
  end

  def create
    @manual = Manual.new(manual_params)
    if @manual.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
    @team = @manual.team
    @comment = Comment.new
    @comments = @manual.comments.includes(:user)
  end

  def edit
    @team = @manual.team
    unless current_user.id == @manual.user_id
      redirect_to action: :show
    end
  end

  def update
    @team = @manual.team
    if @manual.update(manual_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    manual = Manual.find(params[:id])
    unless current_user.id == manual.user_id
      redirect_to action: :show
    end
    manual.destroy
    return redirect_to action: :index
  end

  def search
    if params[:q]&.dig(:title)
      squished_keywords = params[:q][:title].squish
      params[:q][:title_cont_any] = squished_keywords.split(" ")
    end
    @q = Manual.ransack(params[:q])
    @manuals = @q.result
  end

  def each
    @team = Team.find(params[:team_id])
    @manuals = Manual.includes(:user).order("created_at DESC").page(params[:page]).per(20)
  end

  private
  def manual_params
    params.require(:manual).permit(:title, :manual_text, :team_id, :shiryo).merge(user_id: current_user.id)
  end

  def set_manual
    @manual = Manual.find(params[:id])
  end
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/views/manuals/_form.html.erb
<div class="manual-create-form">
  <%= form_with(model: @manual, local: true) do |form| %>
    <%= render 'layouts/error_messages', model: form.object %>
    <div class="manual-field">
      <select name="manual[team_id]">
        <option value="">マニュアルを投稿するチームを選ぶ</option>
        <% Team.where(id: current_user.teams.ids).each do |team| %>
          <option value=<%= team.id %>><%= team.name %></option>
        <% end %>
      </select>
    </div>
    <div class="manual-field">
      <%= form.text_field :title, placeholder: "タイトル", size: "40" %>
    </div>
    <div class="manual-field">
      <%= form.text_area :manual_text, placeholder: "詳細", size: "80x30" %>
    </div>
    <div class="manual-field">
      <%= form.file_field :shiryo%>
    </div>
    <% if local_assigns[:edit_flag].present? %>
      <%= form_with(model: @manual, local: true) do |form| %>
        <div class="manual-field-btn">
          <%= form.submit "確定する", class: "btn btn-danger" %>
        </div>
      <% end %>
    <% else %>
      <%= form_with(model: @manual, local: true) do |form| %>
        <div class="manual-field-btn">
          <%= form.submit "投稿する", class: "btn btn-danger" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/manuals/_search.html.erb
<div class="search">
  <div class="search-title">マニュアル検索</div>
  <div class="field">
    <%= search_form_for Manual.ransack(params[:q]), url: search_manuals_path do |f| %>
      <div class="search-field">
        <% f.label :team_id, 'チーム' %>
        <%= f.collection_select(:team_id_in, current_user.teams, :id, :name, {include_blank: "チームを選択する"} )%>
      </div>
      <div class="search-field">
        <% f.label :title_cont, 'タイトル' %>
        <%= f.text_field :title_cont, placeholder: 'キーワードで探す', size: "15" %>
      </div>
      <div class="search-field">
        <%= f.label :submit, class: "search-button" do %>
          <input type= "submit" value="検索" class="btn btn-danger search-btn">
          <%= f.submit :submit, id: "q_submit", style: "display: none;" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/manuals/each.html.erb
<h2>マニュアル</h2>
<% breadcrumb :manual_each, @team %>

<%# マニュアルの新規作成 %>
<div class="manual-create">
  <%= link_to "マニュアルを作成する", new_manual_path, class: "btn btn-outline-danger" %>
</div>

<div class="manual">
  <div class="manual-body">
    <div class="manual-all">マニュアル一覧</div>
      <% @team.manuals.each do |manual| %>
        <div class="manuals">
          <div class="news">
            <div class="newlabel">
              <%= render 'shared/new_label' if manual.new_arrival? %>
            </div>
            <%= link_to manual.title, manual_path(manual.id), method: :get %>
          </div>
        </div>
      <% end %>
  </div>

  <%# 検索 %>
  <div class="search-body">
    <%= render 'search', url: search_manuals_path, q: @q %>
  </div>
</div>

app/views/manuals/edit.html.erb
<h2>マニュアル</h2>
<% breadcrumb :manual_edit, @manual, @team %>
<div class="manual-container">
  <div class="manual">
    <div class="manual-body">
      <div class="manual-all">マニュアル編集</div>
    </div>
  </div>
  <div class="manual-form">
    <%= render partial: "form", locals: {manual: @manual, edit_flag: true} %>
  </div>
</div>

app/views/manuals/index.html.erb
<h2>マニュアル</h2>
<% breadcrumb :manual_index %>

<%# マニュアルの新規作成 %>
<div class="manual-create">
  <%= link_to "マニュアルを作成する", new_manual_path, class: "btn btn-outline-danger" %>
</div>

<div class="manual">
  <%# 各チームのマニュアルへのリンク %>
  <div class="manual-body">
    <div class="manual-team">所属グループを選ぶ</div>
    <div class="manual-team-each">
      <% current_user.teams.each do |team| %>
        <span class="migi">▶︎</span> <%= link_to team.name, {controller: "manuals", action: "each", team_id: team.id}, id: team.id, class: "link" %><br>
      <% end %>
    </div>

    <%# 所属チームごとのマニュアルタイトル一覧 %>
    <div class="manual-team">所属グループのマニュアル一覧</div>
    <div class="panel-group" id="accordion">
      <% current_user.teams.each do |team| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%=team.id%>">
                <%= team.name %>
              </a>
            </div>
          </div>
          <% team.manuals.each do |manual| %>
            <div id="collapse-<%=team.id%>" class="panel-collapse collapse in">
              <div class="panel-body">
                <div class="news">
                  <div class="newlabel">
                    <%= render 'shared/new_label' if manual.new_arrival? %>
                  </div>
                  <%= link_to manual.title, manual_path(manual.id), method: :get, class: "link" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%# 検索 %>
  <div class="search-body">
    <%= render 'search', url: search_manuals_path, q: @q %>
  </div>

</div>

app/views/manuals/new.html.erb
<h2>マニュアル</h2>
<% breadcrumb :manual_new %>

<div class="manual-container">
  <div class="manual">
    <div class="manual-body">
      <div class="manual-all">マニュアル新規作成</div>
    </div>
  </div>
  <div class="manual-form">
    <%= render partial: "form", locals: {manual: @manual} %>
  </div>
</div>

app/views/manuals/search.html.erb
<h2>マニュアル検索結果</h2>
<% breadcrumb :manual_search %>

<%# マニュアルの新規作成 %>
<div class="manual-create">
  <%= link_to "マニュアルを作成する", new_manual_path, class: "btn btn-outline-danger" %>
</div>

<div class="manual">
  <%# マニュアル検索結果 %>
  <div class="manual-body">
    <% if @manuals.present? %>
      <% @manuals.each do |manual| %>
      <div class="manual-team">
        <%= manual.team.name %>のマニュアル
      </div>
      <ul>
        <li>
          <%= link_to manual.title, manual_path(manual.id), method: :get, class: "link"%><br>
          　　　　　作成日：<%= manual.created_at.strftime('%Y年%m月%d日') %>
        </li>
      </ul>
      <% end %>
    <% else %>
      <p>キーワードに該当するマニュアルはありません</p>
    <% end %>
  </div>

  <div class="search-body">
    <%= render 'search', url: search_manuals_path, q: @q %>
  </div>
</div>

app/views/manuals/show.html.erb
<h2>マニュアル</h2>
<% breadcrumb :manual_show, @manual, @team %>

<div class="manual-create">
  <%= link_to "マニュアルを作成する", new_manual_path, class: "btn btn-outline-danger" %>
</div>

<div class="manual">
  <div class="manual-body">
    <div class="manual-all">
      <%= @manual.title %>
    </div>

    <div class="edit">
      <% if current_user.id == @manual.user_id %>
        <%= link_to "編集", edit_manual_path(@manual.id), class: "link" %>
        <%= link_to "削除", manual_path(@manual.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "link" %>
      <% end %>
    </div>

    <div class="manual-cont">チーム名</div>
    <div class="mnl">
      <%= @manual.team.name%>
    </div>
    <div class="manual-cont">マニュアルタイトル</div>
    <div class="mnl">
      <%= @manual.title %>
    </div>
    <div class="manual-cont">マニュアル詳細</div>
    <div class="mnl">
      <%= simple_format(@manual.manual_text) %>
    </div>
    <% if @manual.shiryo? %>
      <div class="manual-cont">添付資料</div>
      <div class="mnl">
        <%= link_to '添付資料を開く', @manual.shiryo.url, target: :_blank, rel: "noopener noreferrer", class: "link" %>
      </div>
    <% end %>
    <div class="manual-cont">マニュアル作成日</div>
    <div class="mnl">
      <%= @manual.created_at.strftime('%Y/%m/%d') %>
    </div>
    <div class="manual-cont">マニュアル作成者</div>
    <div class="mnl">
      <%= @manual.user.full_name %>
    </div>

    <%# 備考機能 %>
    <div class="comment-cont">
      <div class="comments">
        <div class="manual-cont">備考</div>
        <% @comments.each do |comment| %>
          <p>
            <%= simple_format(comment.comment) %>
            <br>
            <strong>記入者：<%= comment.user.full_name %></strong>
          </p>
          <% if current_user.id == comment.user_id%>
            備考の
            <%= link_to "編集", edit_manual_comment_path(@manual, comment), class: "link" %>
            <%= link_to "削除", manual_comment_path(@manual, comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "link" %>
          <% end %>
        <% end %>
      </div>

      <div class="comment-form">
        <% if current_user.id == @manual.user_id %>
          <%= form_with(model: [@manual, @comment], local: true) do |form| %>
            <%= form.text_area :comment, placeholder: "備考を記入する", cols: "80", rows: "10" %>
            <%= form.submit "追加", class: "btn btn-danger" %>
          <% end %>
        <% end %>
      </div>
  </div>
</div>